---

apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    service: registry
spec:
  selector:
    app: registry
  type: ClusterIP
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
  containers:
  - name: registry
    image: registry:2
    imagePullPolicy: IfNotPresent
    ports:
     - name: registry
       containerPort: 5000
       protocol: TCP
    
