version: '3.8'
services:
  clickhouse:
    build:
      context: ./apps/clickhouse
      dockerfile: Dockerfile
    container_name: clickhouse
    hostname: clickhouse
    command: ["/script/init.sh", "1"]
    ports:
      - 8123:8123
      - 9000:9000
    user: root:root
    depends_on:
      - zookeeper

  zookeeper:
    build:
      context: ./apps/zookeeper
      dockerfile: Dockerfile
    container_name: zookeeper
    hostname: zookeeper
    command: ["/script/init.sh", "1"]
    ports:
      - 2181:2181
    user: root:root  
